version: '3.1'
services:
  web2py-gunicorn:
    build: .
    ports:
      - "80:8000"
    networks:
      - postgres-network
    volumes:
      - ./applications:/home/web2py/web2py/applications/

  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=productDb
    ports: 
      - "5432:5432"
    restart: always
    networks:
      - postgres-network
    volumes: 
      - ./database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=danielcatto@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - '5050:80'
    restart: always
    networks:
      - postgres-network
    volumes: 
      - ./pgadmin:/root/.pgadmin

volumes:
  applications:
  database-data:
  pgadmin:

networks: 
  postgres-network:
    driver: bridge
